export enum IsoCountryCode {
  AD = "AD",
  AE = "AE",
  AF = "AF",
  AG = "AG",
  AI = "AI",
  AL = "AL",
  AM = "AM",
  AO = "AO",
  AR = "AR",
  AS = "AS",
  AT = "AT",
  AU = "AU",
  AW = "AW",
  AX = "AX",
  AZ = "AZ",
  BA = "BA",
  BB = "BB",
  BD = "BD",
  BE = "BE",
  BF = "BF",
  BG = "BG",
  BH = "BH",
  BI = "BI",
  BJ = "BJ",
  BL = "BL",
  BM = "BM",
  BN = "BN",
  BO = "BO",
  BR = "BR",
  BS = "BS",
  BT = "BT",
  BV = "BV",
  BW = "BW",
  BY = "BY",
  BZ = "BZ",
  CA = "CA",
  CC = "CC",
  CD = "CD",
  CF = "CF",
  CG = "CG",
  CH = "CH",
  CI = "CI",
  CK = "CK",
  CL = "CL",
  CM = "CM",
  CN = "CN",
  CO = "CO",
  CR = "CR",
  CU = "CU",
  CV = "CV",
  CW = "CW",
  CX = "CX",
  CY = "CY",
  CZ = "CZ",
  DE = "DE",
  DJ = "DJ",
  DK = "DK",
  DM = "DM",
  DO = "DO",
  DZ = "DZ",
  EC = "EC",
  EE = "EE",
  EG = "EG",
  EH = "EH",
  ER = "ER",
  ES = "ES",
  ET = "ET",
  FI = "FI",
  FJ = "FJ",
  FK = "FK",
  FM = "FM",
  FO = "FO",
  FR = "FR",
  GA = "GA",
  GB = "GB",
  GD = "GD",
  GE = "GE",
  GF = "GF",
  GG = "GG",
  GH = "GH",
  GI = "GI",
  GL = "GL",
  GM = "GM",
  GN = "GN",
  GP = "GP",
  GQ = "GQ",
  GR = "GR",
  GS = "GS",
  GT = "GT",
  GU = "GU",
  GW = "GW",
  GY = "GY",
  HK = "HK",
  HM = "HM",
  HN = "HN",
  HR = "HR",
  HT = "HT",
  HU = "HU",
  ID = "ID",
  IE = "IE",
  IL = "IL",
  IM = "IM",
  IN = "IN",
  IO = "IO",
  IQ = "IQ",
  IR = "IR",
  IS = "IS",
  IT = "IT",
  JE = "JE",
  JM = "JM",
  JO = "JO",
  JP = "JP",
  KE = "KE",
  KG = "KG",
  KH = "KH",
  KI = "KI",
  KM = "KM",
  KN = "KN",
  KP = "KP",
  KR = "KR",
  KW = "KW",
  KY = "KY",
  KZ = "KZ",
  LA = "LA",
  LB = "LB",
  LC = "LC",
  LI = "LI",
  LK = "LK",
  LR = "LR",
  LS = "LS",
  LT = "LT",
  LU = "LU",
  LV = "LV",
  LY = "LY",
  MA = "MA",
  MC = "MC",
  MD = "MD",
  ME = "ME",
  MF = "MF",
  MG = "MG",
  MH = "MH",
  MK = "MK",
  ML = "ML",
  MM = "MM",
  MN = "MN",
  MO = "MO",
  MP = "MP",
  MQ = "MQ",
  MR = "MR",
  MS = "MS",
  MT = "MT",
  MU = "MU",
  MV = "MV",
  MW = "MW",
  MX = "MX",
  MY = "MY",
  MZ = "MZ",
  NA = "NA",
  NC = "NC",
  NE = "NE",
  NF = "NF",
  NG = "NG",
  NI = "NI",
  NL = "NL",
  NO = "NO",
  NP = "NP",
  NR = "NR",
  NU = "NU",
  NZ = "NZ",
  OM = "OM",
  PA = "PA",
  PE = "PE",
  PF = "PF",
  PG = "PG",
  PH = "PH",
  PK = "PK",
  PL = "PL",
  PM = "PM",
  PN = "PN",
  PR = "PR",
  PS = "PS",
  PT = "PT",
  PW = "PW",
  PY = "PY",
  QA = "QA",
  RE = "RE",
  RO = "RO",
  RS = "RS",
  RU = "RU",
  RW = "RW",
  SA = "SA",
  SB = "SB",
  SC = "SC",
  SD = "SD",
  SE = "SE",
  SG = "SG",
  SH = "SH",
  SI = "SI",
  SJ = "SJ",
  SK = "SK",
  SL = "SL",
  SM = "SM",
  SN = "SN",
  SO = "SO",
  SR = "SR",
  SS = "SS",
  ST = "ST",
  SV = "SV",
  SX = "SX",
  SY = "SY",
  SZ = "SZ",
  TC = "TC",
  TD = "TD",
  TF = "TF",
  TG = "TG",
  TH = "TH",
  TJ = "TJ",
  TK = "TK",
  TL = "TL",
  TM = "TM",
  TN = "TN",
  TO = "TO",
  TR = "TR",
  TT = "TT",
  TV = "TV",
  TW = "TW",
  TZ = "TZ",
  UA = "UA",
  UG = "UG",
  UM = "UM",
  US = "US",
  UY = "UY",
  UZ = "UZ",
  VA = "VA",
  VC = "VC",
  VE = "VE",
  VG = "VG",
  VI = "VI",
  VN = "VN",
  VU = "VU",
  WF = "WF",
  WS = "WS",
  YE = "YE",
  YT = "YT",
  ZA = "ZA",
  ZM = "ZM",
  ZW = "ZW",
}

/**
 * Pass in an ISO country code string (lower or upper case) to get an
 * IsoCountryCoe.
 */
export function getCountryCode(isoCountryCodeStr: string): IsoCountryCode {
  const isoCountryCode =
    IsoCountryCode[
      isoCountryCodeStr.toUpperCase() as keyof typeof IsoCountryCode
    ];
  if (isoCountryCode === undefined) {
    throw new Error(`Country code ${isoCountryCodeStr} does not exist`);
  }

  return isoCountryCode;
}

export enum SovereigntyLevel {
  Disputed,
  Territory,
  UNMemberState,
  UNObserver,
}

export interface CountryDatum {
  isoCountryCode: IsoCountryCode;
  countryName: string;
  capitalCity: string | null;
  population: number;
  sovereigntyLevel: SovereigntyLevel;
  parentCountry?: string;
  wikiUrl: string;
}

/**
 * The population is stored as a string because JavaScript doesn't have
 * integers. Also isoCountryCode is just a string.
 */
interface RawCountryDatum {
  isoCountryCode: string;
  countryName: string;
  capitalCity: string | null;
  population: string;
  sovereigntyLevel: SovereigntyLevel;
  wikiUrl: string;
  parentCountry?: string;
}

// JavaScript object representation of country data (with unparsed
// populations).
type CountryDataMapRecord = Record<string, RawCountryDatum>;
// JavaScript Map representation of country data (with parsed
// populations).
type RawCountryDataMap = Map<IsoCountryCode, CountryDatum>;

const rawCountryData: CountryDataMapRecord = {
  /* A */
  AD: {
    isoCountryCode: "AD",
    countryName: "Andorra",
    capitalCity: "Andorra la Vella",
    population: "84000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Andorra",
  },
  AE: {
    isoCountryCode: "AE",
    countryName: "United Arab Emirates",
    capitalCity: "Abu Dhabi",
    population: "4975593",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/United_Arab_Emirates",
  },
  AF: {
    isoCountryCode: "AF",
    countryName: "Afghanistan",
    capitalCity: "Kabul",
    population: "29121286",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Afghanistan",
  },
  AG: {
    isoCountryCode: "AG",
    countryName: "Antigua And Barbuda",
    capitalCity: "St. John's",
    population: "86754",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Antigua_and_Barbuda",
  },
  AI: {
    isoCountryCode: "AI",
    countryName: "Anguilla",
    capitalCity: "The Valley",
    population: "13254",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Anguilla",
  },
  AL: {
    isoCountryCode: "AL",
    countryName: "Albania",
    capitalCity: "Tirana",
    population: "2986952",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Albania",
  },
  AM: {
    isoCountryCode: "AM",
    countryName: "Armenia",
    capitalCity: "Yerevan",
    population: "2968000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Armenia",
  },
  AO: {
    isoCountryCode: "AO",
    countryName: "Angola",
    capitalCity: "Luanda",
    population: "13068161",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Angola",
  },
  AR: {
    isoCountryCode: "AR",
    countryName: "Argentina",
    capitalCity: "Buenos Aires",
    population: "41343201",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Argentina",
  },
  AS: {
    isoCountryCode: "AS",
    countryName: "American Samoa",
    capitalCity: "Pago Pago",
    population: "57881",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
    wikiUrl: "https://en.wikipedia.org/wiki/American_Samoa",
  },
  AT: {
    isoCountryCode: "AT",
    countryName: "Austria",
    capitalCity: "Vienna",
    population: "8205000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Austria",
  },
  AU: {
    isoCountryCode: "AU",
    countryName: "Australia",
    capitalCity: "Canberra",
    population: "21515754",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Australia",
  },
  AW: {
    isoCountryCode: "AW",
    countryName: "Aruba",
    capitalCity: "Oranjestad",
    population: "71566",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NL",
    wikiUrl: "https://en.wikipedia.org/wiki/Aruba",
  },
  AX: {
    isoCountryCode: "AX",
    countryName: "Aland Islands",
    capitalCity: "Mariehamn",
    population: "26711",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FI",
    wikiUrl: "https://en.wikipedia.org/wiki/%C3%85land",
  },
  AZ: {
    isoCountryCode: "AZ",
    countryName: "Azerbaijan",
    capitalCity: "Baku",
    population: "8303512",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Azerbaijan",
  },

  /* B */
  BA: {
    isoCountryCode: "BA",
    countryName: "Bosnia and Herzegovina",
    capitalCity: "Sarajevo",
    population: "4590000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Bosnia_and_Herzegovina",
  },
  BB: {
    isoCountryCode: "BB",
    countryName: "Barbados",
    capitalCity: "Bridgetown",
    population: "285653",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Barbados",
  },
  BD: {
    isoCountryCode: "BD",
    countryName: "Bangladesh",
    capitalCity: "Dhaka",
    population: "156118464",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Bangladesh",
  },
  BE: {
    isoCountryCode: "BE",
    countryName: "Belgium",
    capitalCity: "Brussels",
    population: "10403000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Belgium",
  },
  BF: {
    isoCountryCode: "BF",
    countryName: "Burkina Faso",
    capitalCity: "Ouagadougou",
    population: "16241811",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Burkina_Faso",
  },
  BG: {
    isoCountryCode: "BG",
    countryName: "Bulgaria",
    capitalCity: "Sofia",
    population: "7148785",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Bulgaria",
  },
  BH: {
    isoCountryCode: "BH",
    countryName: "Bahrain",
    capitalCity: "Manama",
    population: "738004",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Bahrain",
  },
  BI: {
    isoCountryCode: "BI",
    countryName: "Burundi",
    capitalCity: "Gitega",
    population: "9863117",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Burundi",
  },
  BJ: {
    isoCountryCode: "BJ",
    countryName: "Benin",
    capitalCity: "Porto-Novo",
    population: "9056010",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Benin",
  },
  BL: {
    isoCountryCode: "BL",
    countryName: "Saint Barthelemy",
    capitalCity: "Gustavia",
    population: "8450",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/Saint_Barth%C3%A9lemy",
  },
  BM: {
    isoCountryCode: "BM",
    countryName: "Bermuda",
    capitalCity: "Hamilton",
    population: "65365",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Bermuda",
  },
  BN: {
    isoCountryCode: "BN",
    countryName: "Brunei",
    capitalCity: "Bandar Seri Begawan",
    population: "395027",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Brunei",
  },
  BO: {
    isoCountryCode: "BO",
    countryName: "Bolivia",
    capitalCity: "La Paz",
    population: "9947418",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Bolivia",
  },
  BR: {
    isoCountryCode: "BR",
    countryName: "Brazil",
    capitalCity: "Brasília",
    population: "201103330",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Brazil",
  },
  BS: {
    isoCountryCode: "BS",
    countryName: "Bahamas",
    capitalCity: "Nassau",
    population: "301790",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/The_Bahamas",
  },
  BT: {
    isoCountryCode: "BT",
    countryName: "Bhutan",
    capitalCity: "Thimphu",
    population: "699847",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Bhutan",
  },
  BV: {
    isoCountryCode: "BV",
    countryName: "Bouvet Island",
    capitalCity: null,
    population: "0",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NO",
    wikiUrl: "https://en.wikipedia.org/wiki/Bouvet_Island",
  },
  BW: {
    isoCountryCode: "BW",
    countryName: "Botswana",
    capitalCity: "Gaborone",
    population: "2029307",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Botswana",
  },
  BY: {
    isoCountryCode: "BY",
    countryName: "Belarus",
    capitalCity: "Minsk",
    population: "9685000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Belarus",
  },
  BZ: {
    isoCountryCode: "BZ",
    countryName: "Belize",
    capitalCity: "Belmopan",
    population: "314522",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Belize",
  },

  /* C */
  CA: {
    isoCountryCode: "CA",
    countryName: "Canada",
    capitalCity: "Ottawa",
    population: "33679000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Canada",
  },
  CC: {
    isoCountryCode: "CC",
    countryName: "Cocos (Keeling) Islands",
    capitalCity: "West Island",
    population: "628",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
    wikiUrl: "https://en.wikipedia.org/wiki/Cocos_(Keeling)_Islands",
  },
  CD: {
    isoCountryCode: "CD",
    countryName: "The Democratic Republic of the Congo",
    capitalCity: "Kinshasa",
    population: "70916439",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Democratic_Republic_of_the_Congo",
  },
  CF: {
    isoCountryCode: "CF",
    countryName: "Central African Republic",
    capitalCity: "Bangui",
    population: "4844927",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Central_African_Republic",
  },
  CG: {
    isoCountryCode: "CG",
    countryName: "The Republic of the Congo",
    capitalCity: "Brazzaville",
    population: "3039126",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Republic_of_the_Congo",
  },
  CH: {
    isoCountryCode: "CH",
    countryName: "Switzerland",
    capitalCity: "Bern",
    population: "7581000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Switzerland",
  },
  CI: {
    isoCountryCode: "CI",
    countryName: "Cote D'Ivoire",
    capitalCity: "Yamoussoukro",
    population: "21058798",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Ivory_Coast",
  },
  CK: {
    isoCountryCode: "CK",
    countryName: "Cook Islands",
    capitalCity: "Avarua",
    population: "21388",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NZ",
    wikiUrl: "https://en.wikipedia.org/wiki/Cook_Islands",
  },
  CL: {
    isoCountryCode: "CL",
    countryName: "Chile",
    capitalCity: "Santiago",
    population: "16746491",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Chile",
  },
  CM: {
    isoCountryCode: "CM",
    countryName: "Cameroon",
    capitalCity: "Yaoundé",
    population: "19294149",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Cameroon",
  },
  CN: {
    isoCountryCode: "CN",
    countryName: "China",
    capitalCity: "Beijing",
    population: "1330044000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/China",
  },
  CO: {
    isoCountryCode: "CO",
    countryName: "Colombia",
    capitalCity: "Bogotá",
    population: "47790000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Colombia",
  },
  CR: {
    isoCountryCode: "CR",
    countryName: "Costa Rica",
    capitalCity: "San José",
    population: "4516220",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Costa_Rica",
  },
  CU: {
    isoCountryCode: "CU",
    countryName: "Cuba",
    capitalCity: "Havana",
    population: "11423000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Cuba",
  },
  CV: {
    isoCountryCode: "CV",
    countryName: "Cabo Verde",
    capitalCity: "Praia",
    population: "508659",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Cape_Verde",
  },
  CW: {
    isoCountryCode: "CW",
    countryName: "Curaçao",
    capitalCity: "Willemstad",
    population: "158665",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NL",
    wikiUrl: "https://en.wikipedia.org/wiki/Cura%C3%A7ao",
  },
  CX: {
    isoCountryCode: "CX",
    countryName: "Christmas Island",
    capitalCity: "Flying Fish Cove",
    population: "1500",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
    wikiUrl: "https://en.wikipedia.org/wiki/Christmas_Island",
  },
  CY: {
    isoCountryCode: "CY",
    countryName: "Cyprus",
    capitalCity: "Nicosia",
    population: "1102677",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Cyprus",
  },
  CZ: {
    isoCountryCode: "CZ",
    countryName: "Czech Republic",
    capitalCity: "Prague",
    population: "10476000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Czech_Republic",
  },

  /* D */
  DE: {
    isoCountryCode: "DE",
    countryName: "Germany",
    capitalCity: "Berlin",
    population: "81802257",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Germany",
  },
  DJ: {
    isoCountryCode: "DJ",
    countryName: "Djibouti",
    capitalCity: "Djibouti",
    population: "740528",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Djibouti",
  },
  DK: {
    isoCountryCode: "DK",
    countryName: "Denmark",
    capitalCity: "Copenhagen",
    population: "5484000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Denmark",
  },
  DM: {
    isoCountryCode: "DM",
    countryName: "Dominica",
    capitalCity: "Roseau",
    population: "72813",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Dominica",
  },
  DO: {
    isoCountryCode: "DO",
    countryName: "Dominican Republic",
    capitalCity: "Santo Domingo",
    population: "9823821",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Dominican_Republic",
  },
  DZ: {
    isoCountryCode: "DZ",
    countryName: "Algeria",
    capitalCity: "Algiers",
    population: "34586184",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Algeria",
  },

  /* E */
  EC: {
    isoCountryCode: "EC",
    countryName: "Ecuador",
    capitalCity: "Quito",
    population: "14790608",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Ecuador",
  },
  EE: {
    isoCountryCode: "EE",
    countryName: "Estonia",
    capitalCity: "Tallinn",
    population: "1291170",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Estonia",
  },
  EG: {
    isoCountryCode: "EG",
    countryName: "Egypt",
    capitalCity: "Cairo",
    population: "80471869",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Egypt",
  },
  EH: {
    isoCountryCode: "EH",
    countryName: "Western Sahara",
    capitalCity: null,
    population: "273008",
    sovereigntyLevel: SovereigntyLevel.Disputed,
    wikiUrl: "https://en.wikipedia.org/wiki/Western_Sahara",
  },
  ER: {
    isoCountryCode: "ER",
    countryName: "Eritrea",
    capitalCity: "Asmara",
    population: "5792984",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Eritrea",
  },
  ES: {
    isoCountryCode: "ES",
    countryName: "Spain",
    capitalCity: "Madrid",
    population: "46505963",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Spain",
  },
  ET: {
    isoCountryCode: "ET",
    countryName: "Ethiopia",
    capitalCity: "Addis Ababa",
    population: "88013491",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Ethiopia",
  },

  /* F */
  FI: {
    isoCountryCode: "FI",
    countryName: "Finland",
    capitalCity: "Helsinki",
    population: "5244000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Finland",
  },
  FJ: {
    isoCountryCode: "FJ",
    countryName: "Fiji",
    capitalCity: "Suva",
    population: "875983",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Fiji",
  },
  FK: {
    isoCountryCode: "FK",
    countryName: "Falkland Islands (Malvinas)",
    capitalCity: "Stanley",
    population: "2638",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Falkland_Islands",
  },
  FM: {
    isoCountryCode: "FM",
    countryName: "Micronesia, Federated States Of",
    capitalCity: "Palikir",
    population: "107708",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Federated_States_of_Micronesia",
  },
  FO: {
    isoCountryCode: "FO",
    countryName: "Faroe Islands",
    capitalCity: "Tórshavn",
    population: "48228",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "DK",
    wikiUrl: "https://en.wikipedia.org/wiki/Faroe_Islands",
  },
  FR: {
    isoCountryCode: "FR",
    countryName: "France",
    capitalCity: "Paris",
    population: "64768389",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/France",
  },

  /* G */
  GA: {
    isoCountryCode: "GA",
    countryName: "Gabon",
    capitalCity: "Libreville",
    population: "1545255",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Gabon",
  },
  GB: {
    isoCountryCode: "GB",
    countryName: "United Kingdom",
    capitalCity: "London",
    population: "62348447",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/United_Kingdom",
  },
  GD: {
    isoCountryCode: "GD",
    countryName: "Grenada",
    capitalCity: "St. George's",
    population: "107818",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Grenada",
  },
  GE: {
    isoCountryCode: "GE",
    countryName: "Georgia",
    capitalCity: "Tbilisi",
    population: "4630000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Georgia_(country)",
  },
  GF: {
    isoCountryCode: "GF",
    countryName: "French Guiana",
    capitalCity: "Cayenne",
    population: "195506",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/French_Guiana",
  },
  GG: {
    isoCountryCode: "GG",
    countryName: "Guernsey",
    capitalCity: "St. Peter Port",
    population: "65228",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Guernsey",
  },
  GH: {
    isoCountryCode: "GH",
    countryName: "Ghana",
    capitalCity: "Accra",
    population: "24339838",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Ghana",
  },
  GI: {
    isoCountryCode: "GI",
    countryName: "Gibraltar",
    capitalCity: "Westside",
    population: "27884",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Gibraltar",
  },
  GL: {
    isoCountryCode: "GL",
    countryName: "Greenland",
    capitalCity: "Nuuk",
    population: "56375",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "DK",
    wikiUrl: "https://en.wikipedia.org/wiki/Greenland",
  },
  GM: {
    isoCountryCode: "GM",
    countryName: "Gambia",
    capitalCity: "Banjul",
    population: "1593256",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/The_Gambia",
  },
  GN: {
    isoCountryCode: "GN",
    countryName: "Guinea",
    capitalCity: "Conakry",
    population: "10324025",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Guinea",
  },
  GP: {
    isoCountryCode: "GP",
    countryName: "Guadeloupe",
    capitalCity: "Basse-Terre",
    population: "443000",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/Guadeloupe",
  },
  GQ: {
    isoCountryCode: "GQ",
    countryName: "Equatorial Guinea",
    capitalCity: "Malabo",
    population: "1014999",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Equatorial_Guinea",
  },
  GR: {
    isoCountryCode: "GR",
    countryName: "Greece",
    capitalCity: "Athens",
    population: "11000000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Greece",
  },
  GS: {
    isoCountryCode: "GS",
    countryName: "South Georgia And Sandwich Isl.",
    capitalCity: "King Edward Point",
    population: "30",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl:
      "https://en.wikipedia.org/wiki/South_Georgia_and_the_South_Sandwich_Islands",
  },
  GT: {
    isoCountryCode: "GT",
    countryName: "Guatemala",
    capitalCity: "Guatemala City",
    population: "13550440",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Guatemala",
  },
  GU: {
    isoCountryCode: "GU",
    countryName: "Guam",
    capitalCity: "Hagåtña",
    population: "159358",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
    wikiUrl: "https://en.wikipedia.org/wiki/Guam",
  },
  GW: {
    isoCountryCode: "GW",
    countryName: "Guinea-Bissau",
    capitalCity: "Bissau",
    population: "1565126",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Guinea-Bissau",
  },
  GY: {
    isoCountryCode: "GY",
    countryName: "Guyana",
    capitalCity: "Georgetown",
    population: "748486",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Guyana",
  },

  /* H */
  HK: {
    isoCountryCode: "HK",
    countryName: "Hong Kong",
    capitalCity: "Hong Kong",
    population: "6898686",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "CN",
    wikiUrl: "https://en.wikipedia.org/wiki/Hong_Kong",
  },
  HM: {
    isoCountryCode: "HM",
    countryName: "Heard Island & Mcdonald Islands",
    capitalCity: null,
    population: "0",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
    wikiUrl: "https://en.wikipedia.org/wiki/Heard_Island_and_McDonald_Islands",
  },
  HN: {
    isoCountryCode: "HN",
    countryName: "Honduras",
    capitalCity: "Tegucigalpa",
    population: "7989415",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Honduras",
  },
  HR: {
    isoCountryCode: "HR",
    countryName: "Croatia",
    capitalCity: "Zagreb",
    population: "4284889",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Croatia",
  },
  HT: {
    isoCountryCode: "HT",
    countryName: "Haiti",
    capitalCity: "Port-au-Prince",
    population: "9648924",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Haiti",
  },
  HU: {
    isoCountryCode: "HU",
    countryName: "Hungary",
    capitalCity: "Budapest",
    population: "9982000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Hungary",
  },

  /* I */
  ID: {
    isoCountryCode: "ID",
    countryName: "Indonesia",
    capitalCity: "Jakarta",
    population: "242968342",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Indonesia",
  },
  IE: {
    isoCountryCode: "IE",
    countryName: "Ireland",
    capitalCity: "Dublin",
    population: "4622917",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Ireland",
  },
  IL: {
    isoCountryCode: "IL",
    countryName: "Israel",
    capitalCity: "Jerusalem",
    // Unrecognized.
    population: "7353985",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Israel",
  },
  IM: {
    isoCountryCode: "IM",
    countryName: "Isle Of Man",
    capitalCity: "Douglas",
    population: "75049",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Isle_of_Man",
  },
  IN: {
    isoCountryCode: "IN",
    countryName: "India",
    capitalCity: "New Delhi",
    population: "1173108018",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/India",
  },
  IO: {
    isoCountryCode: "IO",
    countryName: "British Indian Ocean Territory",
    capitalCity: "Camp Thunder Cove",
    population: "4000",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/British_Indian_Ocean_Territory",
  },
  IQ: {
    isoCountryCode: "IQ",
    countryName: "Iraq",
    capitalCity: "Baghdad",
    population: "29671605",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Iraq",
  },
  IR: {
    isoCountryCode: "IR",
    countryName: "Islamic Republic of Iran",
    capitalCity: "Tehran",
    population: "76923300",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Iran",
  },
  IS: {
    isoCountryCode: "IS",
    countryName: "Iceland",
    capitalCity: "Reykjavík",
    population: "308910",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Iceland",
  },
  IT: {
    isoCountryCode: "IT",
    countryName: "Italy",
    capitalCity: "Rome",
    population: "60340328",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Italy",
  },

  /* J */
  JE: {
    isoCountryCode: "JE",
    countryName: "Jersey",
    capitalCity: "St Helier",
    population: "90812",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Jersey",
  },
  JM: {
    isoCountryCode: "JM",
    countryName: "Jamaica",
    capitalCity: "Kingston",
    population: "2847232",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Jamaica",
  },
  JO: {
    isoCountryCode: "JO",
    countryName: "Jordan",
    capitalCity: "Amman",
    population: "6407085",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Jordan",
  },
  JP: {
    isoCountryCode: "JP",
    countryName: "Japan",
    capitalCity: "Tokyo",
    population: "127288000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Japan",
  },

  /* K */
  KE: {
    isoCountryCode: "KE",
    countryName: "Kenya",
    capitalCity: "Nairobi",
    population: "40046566",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Kenya",
  },
  KG: {
    isoCountryCode: "KG",
    countryName: "Kyrgyzstan",
    capitalCity: "Bishkek",
    population: "5776500",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Kyrgyzstan",
  },
  KH: {
    isoCountryCode: "KH",
    countryName: "Cambodia",
    capitalCity: "Phnom Penh",
    population: "14453680",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Cambodia",
  },
  KI: {
    isoCountryCode: "KI",
    countryName: "Kiribati",
    capitalCity: "South Tarawa",
    population: "92533",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Kiribati",
  },
  KM: {
    isoCountryCode: "KM",
    countryName: "Comoros",
    capitalCity: "Moroni",
    population: "773407",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Comoros",
  },
  KN: {
    isoCountryCode: "KN",
    countryName: "Saint Kitts And Nevis",
    capitalCity: "Basseterre",
    population: "51134",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Saint_Kitts_and_Nevis",
  },
  KP: {
    isoCountryCode: "KP",
    countryName: "North Korea",
    capitalCity: "Pyongyang",
    population: "25549604",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/North_Korea",
  },
  KR: {
    isoCountryCode: "KR",
    countryName: "South Korea",
    capitalCity: "Seoul",
    population: "48422644",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/South_Korea",
  },
  KW: {
    isoCountryCode: "KW",
    countryName: "Kuwait",
    capitalCity: "Kuwait City",
    population: "2789132",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Kuwait",
  },
  KY: {
    isoCountryCode: "KY",
    countryName: "Cayman Islands",
    capitalCity: "George Town",
    population: "44270",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Cayman_Islands",
  },
  KZ: {
    isoCountryCode: "KZ",
    countryName: "Kazakhstan",
    capitalCity: "Astana",
    population: "15340000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Kazakhstan",
  },

  /* L */
  LA: {
    isoCountryCode: "LA",
    countryName: "Lao People's Democratic Republic",
    capitalCity: "Vientiane",
    population: "6368162",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Laos",
  },
  LB: {
    isoCountryCode: "LB",
    countryName: "Lebanon",
    capitalCity: "Beirut",
    population: "4125247",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Lebanon",
  },
  LC: {
    isoCountryCode: "LC",
    countryName: "Saint Lucia",
    capitalCity: "Castries",
    population: "160922",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Saint_Lucia",
  },
  LI: {
    isoCountryCode: "LI",
    countryName: "Liechtenstein",
    capitalCity: "Vaduz",
    population: "35000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Liechtenstein",
  },
  LK: {
    isoCountryCode: "LK",
    countryName: "Sri Lanka",
    capitalCity: "Colombo",
    population: "21513990",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Sri_Lanka",
  },
  LR: {
    isoCountryCode: "LR",
    countryName: "Liberia",
    capitalCity: "Monrovia",
    population: "3685076",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Liberia",
  },
  LS: {
    isoCountryCode: "LS",
    countryName: "Lesotho",
    capitalCity: "Maseru",
    population: "1919552",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Lesotho",
  },
  LT: {
    isoCountryCode: "LT",
    countryName: "Lithuania",
    capitalCity: "Vilnius",
    population: "2944459",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Lithuania",
  },
  LU: {
    isoCountryCode: "LU",
    countryName: "Luxembourg",
    capitalCity: "Luxembourg",
    population: "497538",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Luxembourg",
  },
  LV: {
    isoCountryCode: "LV",
    countryName: "Latvia",
    capitalCity: "Riga",
    population: "2217969",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Latvia",
  },
  LY: {
    isoCountryCode: "LY",
    countryName: "Libya",
    capitalCity: "Tripoli",
    population: "6461454",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Libya",
  },

  /* M */
  MA: {
    isoCountryCode: "MA",
    countryName: "Morocco",
    capitalCity: "Rabat",
    population: "33848242",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Morocco",
  },
  MC: {
    isoCountryCode: "MC",
    countryName: "Monaco",
    capitalCity: "Monaco",
    population: "32965",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Monaco",
  },
  MD: {
    isoCountryCode: "MD",
    countryName: "Moldova",
    capitalCity: "Chișinău",
    population: "4324000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Moldova",
  },
  ME: {
    isoCountryCode: "ME",
    countryName: "Montenegro",
    capitalCity: "Podgorica",
    population: "666730",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Montenegro",
  },
  MF: {
    isoCountryCode: "MF",
    countryName: "Saint Martin",
    capitalCity: "Marigot",
    population: "35925",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/Collectivity_of_Saint_Martin",
  },
  MG: {
    isoCountryCode: "MG",
    countryName: "Madagascar",
    capitalCity: "Antananarivo",
    population: "21281844",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Madagascar",
  },
  MH: {
    isoCountryCode: "MH",
    countryName: "Marshall Islands",
    capitalCity: "Delap-Uliga-Djarrit",
    population: "65859",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Marshall_Islands",
  },
  MK: {
    isoCountryCode: "MK",
    countryName: "North Macedonia",
    capitalCity: "Skopje",
    population: "2062294",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/North_Macedonia",
  },
  ML: {
    isoCountryCode: "ML",
    countryName: "Mali",
    capitalCity: "Bamako",
    population: "13796354",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Mali",
  },
  MM: {
    isoCountryCode: "MM",
    countryName: "Myanmar",
    capitalCity: "Naypyidaw",
    population: "53414374",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Myanmar",
  },
  MN: {
    isoCountryCode: "MN",
    countryName: "Mongolia",
    capitalCity: "Ulaanbaatar",
    population: "3086918",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Mongolia",
  },
  MO: {
    isoCountryCode: "MO",
    countryName: "Macao",
    capitalCity: "Macao",
    population: "449198",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "CN",
    wikiUrl: "https://en.wikipedia.org/wiki/Macau",
  },
  MP: {
    isoCountryCode: "MP",
    countryName: "Northern Mariana Islands",
    capitalCity: "Saipan",
    population: "53883",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
    wikiUrl: "https://en.wikipedia.org/wiki/Northern_Mariana_Islands",
  },
  MQ: {
    isoCountryCode: "MQ",
    countryName: "Martinique",
    capitalCity: "Fort-de-France",
    population: "432900",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/Martinique",
  },
  MR: {
    isoCountryCode: "MR",
    countryName: "Mauritania",
    capitalCity: "Nouakchott",
    population: "3205060",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Mauritania",
  },
  MS: {
    isoCountryCode: "MS",
    countryName: "Montserrat",
    capitalCity: "Plymouth",
    population: "9341",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Montserrat",
  },
  MT: {
    isoCountryCode: "MT",
    countryName: "Malta",
    capitalCity: "Valletta",
    population: "403000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Malta",
  },
  MU: {
    isoCountryCode: "MU",
    countryName: "Mauritius",
    capitalCity: "Port Louis",
    population: "1294104",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Mauritius",
  },
  MV: {
    isoCountryCode: "MV",
    countryName: "Maldives",
    capitalCity: "Malé",
    population: "395650",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Maldives",
  },
  MW: {
    isoCountryCode: "MW",
    countryName: "Malawi",
    capitalCity: "Lilongwe",
    population: "15447500",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Malawi",
  },
  MX: {
    isoCountryCode: "MX",
    countryName: "Mexico",
    capitalCity: "Mexico City",
    population: "112468855",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Mexico",
  },
  MY: {
    isoCountryCode: "MY",
    countryName: "Malaysia",
    capitalCity: "Kuala Lumpur",
    population: "28274729",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Malaysia",
  },
  MZ: {
    isoCountryCode: "MZ",
    countryName: "Mozambique",
    capitalCity: "Maputo",
    population: "22061451",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Mozambique",
  },

  /* N */
  NA: {
    isoCountryCode: "NA",
    countryName: "Namibia",
    capitalCity: "Windhoek",
    population: "2128471",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Namibia",
  },
  NC: {
    isoCountryCode: "NC",
    countryName: "New Caledonia",
    capitalCity: "Nouméa",
    population: "216494",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/New_Caledonia",
  },
  NE: {
    isoCountryCode: "NE",
    countryName: "Niger",
    capitalCity: "Niamey",
    population: "15878271",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Niger",
  },
  NF: {
    isoCountryCode: "NF",
    countryName: "Norfolk Island",
    capitalCity: "Kingston",
    population: "1828",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
    wikiUrl: "https://en.wikipedia.org/wiki/Norfolk_Island",
  },
  NG: {
    isoCountryCode: "NG",
    countryName: "Nigeria",
    capitalCity: "Abuja",
    population: "154000000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Nigeria",
  },
  NI: {
    isoCountryCode: "NI",
    countryName: "Nicaragua",
    capitalCity: "Managua",
    population: "5995928",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Nicaragua",
  },
  NL: {
    isoCountryCode: "NL",
    countryName: "Netherlands",
    capitalCity: "Amsterdam",
    population: "16645000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Netherlands",
  },
  NO: {
    isoCountryCode: "NO",
    countryName: "Norway",
    capitalCity: "Oslo",
    population: "5009150",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Norway",
  },
  NP: {
    isoCountryCode: "NP",
    countryName: "Nepal",
    capitalCity: "Kathmandu",
    population: "28951852",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Nepal",
  },
  NR: {
    isoCountryCode: "NR",
    countryName: "Nauru",
    capitalCity: "Yaren",
    population: "10065",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Nauru",
  },
  NU: {
    isoCountryCode: "NU",
    countryName: "Niue",
    capitalCity: "Alofi",
    population: "2166",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NZ",
    wikiUrl: "https://en.wikipedia.org/wiki/Niue",
  },
  NZ: {
    isoCountryCode: "NZ",
    countryName: "New Zealand",
    capitalCity: "Wellington",
    population: "4252277",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/New_Zealand",
  },

  /* O */
  OM: {
    isoCountryCode: "OM",
    countryName: "Oman",
    capitalCity: "Muscat",
    population: "2967717",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Oman",
  },

  /* P */
  PA: {
    isoCountryCode: "PA",
    countryName: "Panama",
    capitalCity: "Panama City",
    population: "3410676",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Panama",
  },
  PE: {
    isoCountryCode: "PE",
    countryName: "Peru",
    capitalCity: "Lima",
    population: "29907003",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Peru",
  },
  PF: {
    isoCountryCode: "PF",
    countryName: "French Polynesia",
    capitalCity: "Papeete",
    population: "270485",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/French_Polynesia",
  },
  PG: {
    isoCountryCode: "PG",
    countryName: "Papua New Guinea",
    capitalCity: "Port Moresby",
    population: "6064515",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Papua_New_Guinea",
  },
  PH: {
    isoCountryCode: "PH",
    countryName: "Philippines",
    capitalCity: "Manila",
    population: "99900177",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Philippines",
  },
  PK: {
    isoCountryCode: "PK",
    countryName: "Pakistan",
    capitalCity: "Islamabad",
    population: "184404791",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Pakistan",
  },
  PL: {
    isoCountryCode: "PL",
    countryName: "Poland",
    capitalCity: "Warsaw",
    population: "38500000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Poland",
  },
  PM: {
    isoCountryCode: "PM",
    countryName: "Saint Pierre And Miquelon",
    capitalCity: "Saint-Pierre",
    population: "7012",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/Saint_Pierre_and_Miquelon",
  },
  PN: {
    isoCountryCode: "PN",
    countryName: "Pitcairn",
    capitalCity: "Adamstown",
    population: "46",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Pitcairn_Islands",
  },
  PR: {
    isoCountryCode: "PR",
    countryName: "Puerto Rico",
    capitalCity: "San Juan",
    population: "3916632",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
    wikiUrl: "https://en.wikipedia.org/wiki/Puerto_Rico",
  },
  PS: {
    isoCountryCode: "PS",
    countryName: "Palestinian Territory, Occupied",
    capitalCity: "East Jerusalem",
    population: "3800000",
    sovereigntyLevel: SovereigntyLevel.UNObserver,
    wikiUrl: "https://en.wikipedia.org/wiki/Palestinian_territories",
  },
  PT: {
    isoCountryCode: "PT",
    countryName: "Portugal",
    capitalCity: "Lisbon",
    population: "10676000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Portugal",
  },
  PW: {
    isoCountryCode: "PW",
    countryName: "Palau",
    capitalCity: "Ngerulmud",
    population: "19907",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Palau",
  },
  PY: {
    isoCountryCode: "PY",
    countryName: "Paraguay",
    capitalCity: "Asunción",
    population: "6375830",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Paraguay",
  },

  /* Q */
  QA: {
    isoCountryCode: "QA",
    countryName: "Qatar",
    capitalCity: "Doha",
    population: "840926",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Qatar",
  },

  /* R */
  RE: {
    isoCountryCode: "RE",
    countryName: "Reunion",
    capitalCity: "Saint-Denis",
    population: "776948",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/R%C3%A9union",
  },
  RO: {
    isoCountryCode: "RO",
    countryName: "Romania",
    capitalCity: "Bucharest",
    population: "21959278",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Romania",
  },
  RS: {
    isoCountryCode: "RS",
    countryName: "Serbia",
    capitalCity: "Belgrade",
    population: "7344847",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Serbia",
  },
  RU: {
    isoCountryCode: "RU",
    countryName: "Russian Federation",
    capitalCity: "Moscow",
    population: "140702000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Russia",
  },
  RW: {
    isoCountryCode: "RW",
    countryName: "Rwanda",
    capitalCity: "Kigali",
    population: "11055976",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Rwanda",
  },

  /* S */
  SA: {
    isoCountryCode: "SA",
    countryName: "Saudi Arabia",
    capitalCity: "Riyadh",
    population: "25731776",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Saudi_Arabia",
  },
  SB: {
    isoCountryCode: "SB",
    countryName: "Solomon Islands",
    capitalCity: "Honiara",
    population: "559198",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Solomon_Islands",
  },
  SC: {
    isoCountryCode: "SC",
    countryName: "Seychelles",
    capitalCity: "Victoria",
    population: "88340",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Seychelles",
  },
  SD: {
    isoCountryCode: "SD",
    countryName: "Sudan",
    capitalCity: "Khartoum",
    population: "41592539",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Sudan",
  },
  SE: {
    isoCountryCode: "SE",
    countryName: "Sweden",
    capitalCity: "Stockholm",
    population: "9828655",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Sweden",
  },
  SG: {
    isoCountryCode: "SG",
    countryName: "Singapore",
    capitalCity: "Singapore",
    population: "4701069",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Singapore",
  },
  SH: {
    isoCountryCode: "SH",
    countryName: "Saint Helena",
    capitalCity: "Jamestown",
    population: "7460",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Saint_Helena",
  },
  SI: {
    isoCountryCode: "SI",
    countryName: "Slovenia",
    capitalCity: "Ljubljana",
    population: "2007000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Slovenia",
  },
  SJ: {
    isoCountryCode: "SJ",
    countryName: "Svalbard And Jan Mayen",
    capitalCity: null,
    population: "2550",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NO",
    wikiUrl: "https://en.wikipedia.org/wiki/Svalbard_and_Jan_Mayen",
  },
  SK: {
    isoCountryCode: "SK",
    countryName: "Slovakia",
    capitalCity: "Bratislava",
    population: "5455000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Slovakia",
  },
  SL: {
    isoCountryCode: "SL",
    countryName: "Sierra Leone",
    capitalCity: "Freetown",
    population: "5245695",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Sierra_Leone",
  },
  SM: {
    isoCountryCode: "SM",
    countryName: "San Marino",
    capitalCity: "San Marino",
    population: "31477",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/San_Marino",
  },
  SN: {
    isoCountryCode: "SN",
    countryName: "Senegal",
    capitalCity: "Dakar",
    population: "12323252",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Senegal",
  },
  SO: {
    isoCountryCode: "SO",
    countryName: "Somalia",
    capitalCity: "Mogadishu",
    population: "10112453",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Somalia",
  },
  SR: {
    isoCountryCode: "SR",
    countryName: "Suriname",
    capitalCity: "Paramaribo",
    population: "492829",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Suriname",
  },
  SS: {
    isoCountryCode: "SS",
    countryName: "South Sudan",
    capitalCity: "Juba",
    population: "12778250",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/South_Sudan",
  },
  ST: {
    isoCountryCode: "ST",
    countryName: "Sao Tome And Principe",
    capitalCity: "São Tomé",
    population: "211028",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl:
      "https://en.wikipedia.org/wiki/S%C3%A3o_Tom%C3%A9_and_Pr%C3%ADncipe",
  },
  SV: {
    isoCountryCode: "SV",
    countryName: "El Salvador",
    capitalCity: "San Salvador",
    population: "6052064",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/El_Salvador",
  },
  SX: {
    isoCountryCode: "SX",
    countryName: "Sint Maarten",
    capitalCity: "Philipsburg",
    population: "41486",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NL",
    wikiUrl: "https://en.wikipedia.org/wiki/Sint_Maarten",
  },
  SY: {
    isoCountryCode: "SY",
    countryName: "Syrian Arab Republic",
    capitalCity: "Damascus",
    population: "22198110",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Syria",
  },
  SZ: {
    isoCountryCode: "SZ",
    countryName: "Eswatini",
    capitalCity: "Mbabane",
    population: "1354051",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Eswatini",
  },

  /* T */
  TC: {
    isoCountryCode: "TC",
    countryName: "Turks And Caicos Islands",
    capitalCity: "Cockburn Town",
    population: "20556",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/Turks_and_Caicos_Islands",
  },
  TD: {
    isoCountryCode: "TD",
    countryName: "Chad",
    capitalCity: "N'Djamena",
    population: "10543464",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Chad",
  },
  TF: {
    isoCountryCode: "TF",
    countryName: "French Southern Territories",
    capitalCity: "Saint-Pierre",
    population: "140",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl:
      "https://en.wikipedia.org/wiki/French_Southern_and_Antarctic_Lands",
  },
  TG: {
    isoCountryCode: "TG",
    countryName: "Togo",
    capitalCity: "Lomé",
    population: "6587239",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Togo",
  },
  TH: {
    isoCountryCode: "TH",
    countryName: "Thailand",
    capitalCity: "Bangkok",
    population: "67089500",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Thailand",
  },
  TJ: {
    isoCountryCode: "TJ",
    countryName: "Tajikistan",
    capitalCity: "Dushanbe",
    population: "7487489",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Tajikistan",
  },
  TK: {
    isoCountryCode: "TK",
    countryName: "Tokelau",
    capitalCity: null,
    population: "1466",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NZ",
    wikiUrl: "https://en.wikipedia.org/wiki/Tokelau",
  },
  TL: {
    isoCountryCode: "TL",
    countryName: "Timor-Leste",
    capitalCity: "Dili",
    population: "1154625",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/East_Timor",
  },
  TM: {
    isoCountryCode: "TM",
    countryName: "Turkmenistan",
    capitalCity: "Ashgabat",
    population: "4940916",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Turkmenistan",
  },
  TN: {
    isoCountryCode: "TN",
    countryName: "Tunisia",
    capitalCity: "Tunis",
    population: "10589025",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Tunisia",
  },
  TO: {
    isoCountryCode: "TO",
    countryName: "Tonga",
    capitalCity: "Nukuʻalofa",
    population: "122580",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Tonga",
  },
  TR: {
    isoCountryCode: "TR",
    countryName: "Turkey",
    capitalCity: "Ankara",
    population: "77804122",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Turkey",
  },
  TT: {
    isoCountryCode: "TT",
    countryName: "Trinidad And Tobago",
    capitalCity: "Port of Spain",
    population: "1228691",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Trinidad_and_Tobago",
  },
  TV: {
    isoCountryCode: "TV",
    countryName: "Tuvalu",
    capitalCity: "Funafuti",
    population: "10472",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Tuvalu",
  },
  TW: {
    isoCountryCode: "TW",
    countryName: "Taiwan",
    capitalCity: "Taipei",
    population: "22894384",
    sovereigntyLevel: SovereigntyLevel.Disputed,
    wikiUrl: "https://en.wikipedia.org/wiki/Taiwan",
  },
  TZ: {
    isoCountryCode: "TZ",
    countryName: "Tanzania",
    capitalCity: "Dodoma",
    population: "41892895",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Tanzania",
  },

  /* U */
  UA: {
    isoCountryCode: "UA",
    countryName: "Ukraine",
    capitalCity: "Kyiv",
    population: "45415596",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Ukraine",
  },
  UG: {
    isoCountryCode: "UG",
    countryName: "Uganda",
    capitalCity: "Kampala",
    population: "33398682",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Uganda",
  },
  UM: {
    isoCountryCode: "UM",
    countryName: "United States Minor Outlying Islands",
    capitalCity: null,
    population: "0",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
    wikiUrl:
      "https://en.wikipedia.org/wiki/United_States_Minor_Outlying_Islands",
  },
  US: {
    isoCountryCode: "US",
    countryName: "United States",
    capitalCity: "Washington",
    population: "310232863",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/United_States",
  },
  UY: {
    isoCountryCode: "UY",
    countryName: "Uruguay",
    capitalCity: "Montevideo",
    population: "3477000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Uruguay",
  },
  UZ: {
    isoCountryCode: "UZ",
    countryName: "Uzbekistan",
    capitalCity: "Tashkent",
    population: "27865738",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Uzbekistan",
  },

  /* V */
  VA: {
    isoCountryCode: "VA",
    countryName: "The Holy See",
    capitalCity: "Vatican City",
    population: "921",
    sovereigntyLevel: SovereigntyLevel.UNObserver,
    wikiUrl: "https://en.wikipedia.org/wiki/Holy_See",
  },
  VC: {
    isoCountryCode: "VC",
    countryName: "Saint Vincent And Grenadines",
    capitalCity: "Kingstown",
    population: "104217",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Saint_Vincent_and_the_Grenadines",
  },
  VE: {
    isoCountryCode: "VE",
    countryName: "Venezuela",
    capitalCity: "Caracas",
    population: "27223228",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Venezuela",
  },
  VG: {
    isoCountryCode: "VG",
    countryName: "Virgin Islands, British",
    capitalCity: "Road Town",
    population: "21730",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
    wikiUrl: "https://en.wikipedia.org/wiki/British_Virgin_Islands",
  },
  VI: {
    isoCountryCode: "VI",
    countryName: "Virgin Islands, U.S.",
    capitalCity: "Charlotte Amalie",
    population: "108708",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
    wikiUrl: "https://en.wikipedia.org/wiki/United_States_Virgin_Islands",
  },
  VN: {
    isoCountryCode: "VN",
    countryName: "Vietnam",
    capitalCity: "Hanoi",
    population: "89571130",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Vietnam",
  },
  VU: {
    isoCountryCode: "VU",
    countryName: "Vanuatu",
    capitalCity: "Port Vila",
    population: "221552",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Vanuatu",
  },

  /* W */
  WF: {
    isoCountryCode: "WF",
    countryName: "Wallis And Futuna",
    capitalCity: "Mata Utu",
    population: "16025",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/Wallis_and_Futuna",
  },
  WS: {
    isoCountryCode: "WS",
    countryName: "Samoa",
    capitalCity: "Apia",
    population: "192001",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Samoa",
  },

  /* Y */
  YE: {
    isoCountryCode: "YE",
    countryName: "Yemen",
    capitalCity: "Sanaa",
    population: "23495361",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Yemen",
  },
  YT: {
    isoCountryCode: "YT",
    countryName: "Mayotte",
    capitalCity: "Mamoudzou",
    population: "159042",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
    wikiUrl: "https://en.wikipedia.org/wiki/Mayotte",
  },

  /* Z */
  ZA: {
    isoCountryCode: "ZA",
    countryName: "South Africa",
    capitalCity: "Pretoria",
    population: "49000000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/South_Africa",
  },
  ZM: {
    isoCountryCode: "ZM",
    countryName: "Zambia",
    capitalCity: "Lusaka",
    population: "13460305",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Lusaka",
  },
  ZW: {
    isoCountryCode: "ZW",
    countryName: "Zimbabwe",
    capitalCity: "Harare",
    population: "13061000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
    wikiUrl: "https://en.wikipedia.org/wiki/Zimbabwe",
  },
};

/**
 * `CountryDataMap` is the preferred way to access country data.
 * Effectively a wrapper class.
 */
export class CountryDataMap {
  countryDataMap: RawCountryDataMap;

  /**
   * Builds and returns a `CountryDataMap` consisting of all the
   * countries' data.
   */
  static allDataMap(): CountryDataMap {
    const countryDataMap: RawCountryDataMap = new Map();
    for (const isoCountryCodeStr in rawCountryData) {
      const rawCountryDatum = rawCountryData[isoCountryCodeStr];
      const isoCountryCode =
        IsoCountryCode[isoCountryCodeStr as keyof typeof IsoCountryCode];
      const countryDatum: CountryDatum = {
        ...rawCountryDatum,
        isoCountryCode,
        population: Number(rawCountryDatum.population),
      };
      countryDataMap.set(isoCountryCode, countryDatum);
    }

    return new CountryDataMap(countryDataMap);
  }

  constructor(countryDataMap: RawCountryDataMap) {
    this.countryDataMap = countryDataMap;
  }

  /**
   * Produces a `CountryDataMap` of only those countries that match the
   * `filterFn`.
   */
  filter(filterFn: (countryDatum: CountryDatum) => boolean): CountryDataMap {
    const filteredCountryDataMap: RawCountryDataMap = new Map();
    for (const countryDatum of this.countryDataMap.values()) {
      if (!filterFn(countryDatum)) {
        continue;
      }
      filteredCountryDataMap.set(countryDatum.isoCountryCode, countryDatum);
    }

    return new CountryDataMap(filteredCountryDataMap);
  }

  /**
   * Get data for the specified country.
   */
  getDataForCode(isoCountryCode: IsoCountryCode): CountryDatum | null {
    return this.countryDataMap.get(isoCountryCode) || null;
  }

  /**
   * Return an iterator for all the keys in the `CountryDataMap`.
   */
  keys() {
    return this.countryDataMap.keys();
  }

  /**
   * Return an iterator for the country data values in the map.
   */
  [Symbol.iterator]() {
    return this.countryDataMap.values();
  }
}

export default CountryDataMap;
