export enum SovereigntyLevel {
  Disputed,
  Territory,
  UNMemberState,
  UNObserver,
}

interface RawCountryDatum {
  isoCountryCode: string;
  countryName: string;
  population: string;
  sovereigntyLevel: SovereigntyLevel;
  parentCountry?: string;
}

export interface CountryDatum {
  isoCountryCode: string;
  countryName: string;
  population: number;
  sovereigntyLevel: SovereigntyLevel;
  parentCountry?: string;
}

const rawCountryData: Record<string, RawCountryDatum> = {
  AF: {
    isoCountryCode: "AF",
    countryName: "Afghanistan",
    population: "29121286",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AX: {
    isoCountryCode: "AX",
    countryName: "Aland Islands",
    population: "26711",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FI",
  },
  AL: {
    isoCountryCode: "AL",
    countryName: "Albania",
    population: "2986952",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  DZ: {
    isoCountryCode: "DZ",
    countryName: "Algeria",
    population: "34586184",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AS: {
    isoCountryCode: "AS",
    countryName: "American Samoa",
    population: "57881",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
  },
  AD: {
    isoCountryCode: "AD",
    countryName: "Andorra",
    population: "84000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AO: {
    isoCountryCode: "AO",
    countryName: "Angola",
    population: "13068161",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AI: {
    isoCountryCode: "AI",
    countryName: "Anguilla",
    population: "13254",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  AG: {
    isoCountryCode: "AG",
    countryName: "Antigua And Barbuda",
    population: "86754",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AR: {
    isoCountryCode: "AR",
    countryName: "Argentina",
    population: "41343201",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AM: {
    isoCountryCode: "AM",
    countryName: "Armenia",
    population: "2968000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AW: {
    isoCountryCode: "AW",
    countryName: "Aruba",
    population: "71566",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NL",
  },
  AU: {
    isoCountryCode: "AU",
    countryName: "Australia",
    population: "21515754",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AT: {
    isoCountryCode: "AT",
    countryName: "Austria",
    population: "8205000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AZ: {
    isoCountryCode: "AZ",
    countryName: "Azerbaijan",
    population: "8303512",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BS: {
    isoCountryCode: "BS",
    countryName: "Bahamas",
    population: "301790",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BH: {
    isoCountryCode: "BH",
    countryName: "Bahrain",
    population: "738004",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BD: {
    isoCountryCode: "BD",
    countryName: "Bangladesh",
    population: "156118464",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BB: {
    isoCountryCode: "BB",
    countryName: "Barbados",
    population: "285653",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BY: {
    isoCountryCode: "BY",
    countryName: "Belarus",
    population: "9685000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BE: {
    isoCountryCode: "BE",
    countryName: "Belgium",
    population: "10403000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BZ: {
    isoCountryCode: "BZ",
    countryName: "Belize",
    population: "314522",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BJ: {
    isoCountryCode: "BJ",
    countryName: "Benin",
    population: "9056010",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BM: {
    isoCountryCode: "BM",
    countryName: "Bermuda",
    population: "65365",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  BT: {
    isoCountryCode: "BT",
    countryName: "Bhutan",
    population: "699847",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BO: {
    isoCountryCode: "BO",
    countryName: "Bolivia",
    population: "9947418",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BA: {
    isoCountryCode: "BA",
    countryName: "Bosnia and Herzegovina",
    population: "4590000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BW: {
    isoCountryCode: "BW",
    countryName: "Botswana",
    population: "2029307",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BV: {
    isoCountryCode: "BV",
    countryName: "Bouvet Island",
    population: "0",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NO",
  },
  BR: {
    isoCountryCode: "BR",
    countryName: "Brazil",
    population: "201103330",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IO: {
    isoCountryCode: "IO",
    countryName: "British Indian Ocean Territory",
    population: "4000",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  BN: {
    isoCountryCode: "BN",
    countryName: "Brunei Darussalam",
    population: "395027",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BG: {
    isoCountryCode: "BG",
    countryName: "Bulgaria",
    population: "7148785",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BF: {
    isoCountryCode: "BF",
    countryName: "Burkina Faso",
    population: "16241811",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BI: {
    isoCountryCode: "BI",
    countryName: "Burundi",
    population: "9863117",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CV: {
    isoCountryCode: "CV",
    countryName: "Cabo Verde",
    population: "508659",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KH: {
    isoCountryCode: "KH",
    countryName: "Cambodia",
    population: "14453680",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CM: {
    isoCountryCode: "CM",
    countryName: "Cameroon",
    population: "19294149",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CA: {
    isoCountryCode: "CA",
    countryName: "Canada",
    population: "33679000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KY: {
    isoCountryCode: "KY",
    countryName: "Cayman Islands",
    population: "44270",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  CF: {
    isoCountryCode: "CF",
    countryName: "Central African Republic",
    population: "4844927",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TD: {
    isoCountryCode: "TD",
    countryName: "Chad",
    population: "10543464",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CL: {
    isoCountryCode: "CL",
    countryName: "Chile",
    population: "16746491",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CN: {
    isoCountryCode: "CN",
    countryName: "China",
    population: "1330044000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CX: {
    isoCountryCode: "CX",
    countryName: "Christmas Island",
    population: "1500",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
  },
  CC: {
    isoCountryCode: "CC",
    countryName: "Cocos (Keeling) Islands",
    population: "628",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
  },
  CO: {
    isoCountryCode: "CO",
    countryName: "Colombia",
    population: "47790000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KM: {
    isoCountryCode: "KM",
    countryName: "Comoros",
    population: "773407",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CG: {
    isoCountryCode: "CG",
    countryName: "The Republic of the Congo",
    population: "3039126",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CD: {
    isoCountryCode: "CD",
    countryName: "The Democratic Republic of the Congo",
    population: "70916439",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CK: {
    isoCountryCode: "CK",
    countryName: "Cook Islands",
    population: "21388",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NZ",
  },
  CR: {
    isoCountryCode: "CR",
    countryName: "Costa Rica",
    population: "4516220",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CI: {
    isoCountryCode: "CI",
    countryName: "Cote D'Ivoire",
    population: "21058798",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  HR: {
    isoCountryCode: "HR",
    countryName: "Croatia",
    population: "4284889",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CU: {
    isoCountryCode: "CU",
    countryName: "Cuba",
    population: "11423000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CY: {
    isoCountryCode: "CY",
    countryName: "Cyprus",
    population: "1102677",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CZ: {
    isoCountryCode: "CZ",
    countryName: "Czech Republic",
    population: "10476000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  DK: {
    isoCountryCode: "DK",
    countryName: "Denmark",
    population: "5484000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  DJ: {
    isoCountryCode: "DJ",
    countryName: "Djibouti",
    population: "740528",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  DM: {
    isoCountryCode: "DM",
    countryName: "Dominica",
    population: "72813",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  DO: {
    isoCountryCode: "DO",
    countryName: "Dominican Republic",
    population: "9823821",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  EC: {
    isoCountryCode: "EC",
    countryName: "Ecuador",
    population: "14790608",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  EG: {
    isoCountryCode: "EG",
    countryName: "Egypt",
    population: "80471869",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SV: {
    isoCountryCode: "SV",
    countryName: "El Salvador",
    population: "6052064",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GQ: {
    isoCountryCode: "GQ",
    countryName: "Equatorial Guinea",
    population: "1014999",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ER: {
    isoCountryCode: "ER",
    countryName: "Eritrea",
    population: "5792984",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  EE: {
    isoCountryCode: "EE",
    countryName: "Estonia",
    population: "1291170",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ET: {
    isoCountryCode: "ET",
    countryName: "Ethiopia",
    population: "88013491",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  FK: {
    isoCountryCode: "FK",
    countryName: "Falkland Islands (Malvinas)",
    population: "2638",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  FO: {
    isoCountryCode: "FO",
    countryName: "Faroe Islands",
    population: "48228",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "DK",
  },
  FJ: {
    isoCountryCode: "FJ",
    countryName: "Fiji",
    population: "875983",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  FI: {
    isoCountryCode: "FI",
    countryName: "Finland",
    population: "5244000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  FR: {
    isoCountryCode: "FR",
    countryName: "France",
    population: "64768389",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GF: {
    isoCountryCode: "GF",
    countryName: "French Guiana",
    population: "195506",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  PF: {
    isoCountryCode: "PF",
    countryName: "French Polynesia",
    population: "270485",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  TF: {
    isoCountryCode: "TF",
    countryName: "French Southern Territories",
    population: "140",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  GA: {
    isoCountryCode: "GA",
    countryName: "Gabon",
    population: "1545255",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GM: {
    isoCountryCode: "GM",
    countryName: "Gambia",
    population: "1593256",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GE: {
    isoCountryCode: "GE",
    countryName: "Georgia",
    population: "4630000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  DE: {
    isoCountryCode: "DE",
    countryName: "Germany",
    population: "81802257",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GH: {
    isoCountryCode: "GH",
    countryName: "Ghana",
    population: "24339838",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GI: {
    isoCountryCode: "GI",
    countryName: "Gibraltar",
    population: "27884",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  GR: {
    isoCountryCode: "GR",
    countryName: "Greece",
    population: "11000000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GL: {
    isoCountryCode: "GL",
    countryName: "Greenland",
    population: "56375",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "DK",
  },
  GD: {
    isoCountryCode: "GD",
    countryName: "Grenada",
    population: "107818",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GP: {
    isoCountryCode: "GP",
    countryName: "Guadeloupe",
    population: "443000",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  GU: {
    isoCountryCode: "GU",
    countryName: "Guam",
    population: "159358",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
  },
  GT: {
    isoCountryCode: "GT",
    countryName: "Guatemala",
    population: "13550440",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GG: {
    isoCountryCode: "GG",
    countryName: "Guernsey",
    population: "65228",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  GN: {
    isoCountryCode: "GN",
    countryName: "Guinea",
    population: "10324025",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GW: {
    isoCountryCode: "GW",
    countryName: "Guinea-Bissau",
    population: "1565126",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GY: {
    isoCountryCode: "GY",
    countryName: "Guyana",
    population: "748486",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  HT: {
    isoCountryCode: "HT",
    countryName: "Haiti",
    population: "9648924",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  HM: {
    isoCountryCode: "HM",
    countryName: "Heard Island & Mcdonald Islands",
    population: "0",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
  },
  VA: {
    isoCountryCode: "VA",
    countryName: "The Holy See",
    population: "921",
    sovereigntyLevel: SovereigntyLevel.UNObserver,
  },
  HN: {
    isoCountryCode: "HN",
    countryName: "Honduras",
    population: "7989415",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  HK: {
    isoCountryCode: "HK",
    countryName: "Hong Kong",
    population: "6898686",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "CN",
  },
  HU: {
    isoCountryCode: "HU",
    countryName: "Hungary",
    population: "9982000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IS: {
    isoCountryCode: "IS",
    countryName: "Iceland",
    population: "308910",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IN: {
    isoCountryCode: "IN",
    countryName: "India",
    population: "1173108018",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ID: {
    isoCountryCode: "ID",
    countryName: "Indonesia",
    population: "242968342",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IR: {
    isoCountryCode: "IR",
    countryName: "Islamic Republic of Iran",
    population: "76923300",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IQ: {
    isoCountryCode: "IQ",
    countryName: "Iraq",
    population: "29671605",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IE: {
    isoCountryCode: "IE",
    countryName: "Ireland",
    population: "4622917",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IM: {
    isoCountryCode: "IM",
    countryName: "Isle Of Man",
    population: "75049",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  IL: {
    isoCountryCode: "IL",
    countryName: "Israel",
    population: "7353985",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  IT: {
    isoCountryCode: "IT",
    countryName: "Italy",
    population: "60340328",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  JM: {
    isoCountryCode: "JM",
    countryName: "Jamaica",
    population: "2847232",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  JP: {
    isoCountryCode: "JP",
    countryName: "Japan",
    population: "127288000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  JE: {
    isoCountryCode: "JE",
    countryName: "Jersey",
    population: "90812",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  JO: {
    isoCountryCode: "JO",
    countryName: "Jordan",
    population: "6407085",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KZ: {
    isoCountryCode: "KZ",
    countryName: "Kazakhstan",
    population: "15340000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KE: {
    isoCountryCode: "KE",
    countryName: "Kenya",
    population: "40046566",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KI: {
    isoCountryCode: "KI",
    countryName: "Kiribati",
    population: "92533",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KP: {
    isoCountryCode: "KP",
    countryName: "North Korea",
    population: "25549604",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KR: {
    isoCountryCode: "KR",
    countryName: "South Korea",
    population: "48422644",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KW: {
    isoCountryCode: "KW",
    countryName: "Kuwait",
    population: "2789132",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  KG: {
    isoCountryCode: "KG",
    countryName: "Kyrgyzstan",
    population: "5776500",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LA: {
    isoCountryCode: "LA",
    countryName: "Lao People's Democratic Republic",
    population: "6368162",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LV: {
    isoCountryCode: "LV",
    countryName: "Latvia",
    population: "2217969",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LB: {
    isoCountryCode: "LB",
    countryName: "Lebanon",
    population: "4125247",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LS: {
    isoCountryCode: "LS",
    countryName: "Lesotho",
    population: "1919552",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LR: {
    isoCountryCode: "LR",
    countryName: "Liberia",
    population: "3685076",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LY: {
    isoCountryCode: "LY",
    countryName: "Libya",
    population: "6461454",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LI: {
    isoCountryCode: "LI",
    countryName: "Liechtenstein",
    population: "35000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LT: {
    isoCountryCode: "LT",
    countryName: "Lithuania",
    population: "2944459",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LU: {
    isoCountryCode: "LU",
    countryName: "Luxembourg",
    population: "497538",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MO: {
    isoCountryCode: "MO",
    countryName: "Macao",
    population: "449198",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "CN",
  },
  MK: {
    isoCountryCode: "MK",
    countryName: "North Macedonia",
    population: "2062294",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MG: {
    isoCountryCode: "MG",
    countryName: "Madagascar",
    population: "21281844",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MW: {
    isoCountryCode: "MW",
    countryName: "Malawi",
    population: "15447500",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MY: {
    isoCountryCode: "MY",
    countryName: "Malaysia",
    population: "28274729",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MV: {
    isoCountryCode: "MV",
    countryName: "Maldives",
    population: "395650",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ML: {
    isoCountryCode: "ML",
    countryName: "Mali",
    population: "13796354",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MT: {
    isoCountryCode: "MT",
    countryName: "Malta",
    population: "403000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MH: {
    isoCountryCode: "MH",
    countryName: "Marshall Islands",
    population: "65859",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MQ: {
    isoCountryCode: "MQ",
    countryName: "Martinique",
    population: "432900",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  MR: {
    isoCountryCode: "MR",
    countryName: "Mauritania",
    population: "3205060",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MU: {
    isoCountryCode: "MU",
    countryName: "Mauritius",
    population: "1294104",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  YT: {
    isoCountryCode: "YT",
    countryName: "Mayotte",
    population: "159042",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  MX: {
    isoCountryCode: "MX",
    countryName: "Mexico",
    population: "112468855",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  FM: {
    isoCountryCode: "FM",
    countryName: "Micronesia, Federated States Of",
    population: "107708",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MD: {
    isoCountryCode: "MD",
    countryName: "Moldova",
    population: "4324000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MC: {
    isoCountryCode: "MC",
    countryName: "Monaco",
    population: "32965",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MN: {
    isoCountryCode: "MN",
    countryName: "Mongolia",
    population: "3086918",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ME: {
    isoCountryCode: "ME",
    countryName: "Montenegro",
    population: "666730",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MS: {
    isoCountryCode: "MS",
    countryName: "Montserrat",
    population: "9341",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  MA: {
    isoCountryCode: "MA",
    countryName: "Morocco",
    population: "33848242",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MZ: {
    isoCountryCode: "MZ",
    countryName: "Mozambique",
    population: "22061451",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MM: {
    isoCountryCode: "MM",
    countryName: "Myanmar",
    population: "53414374",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NA: {
    isoCountryCode: "NA",
    countryName: "Namibia",
    population: "2128471",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NR: {
    isoCountryCode: "NR",
    countryName: "Nauru",
    population: "10065",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NP: {
    isoCountryCode: "NP",
    countryName: "Nepal",
    population: "28951852",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NL: {
    isoCountryCode: "NL",
    countryName: "Netherlands",
    population: "16645000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NC: {
    isoCountryCode: "NC",
    countryName: "New Caledonia",
    population: "216494",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  NZ: {
    isoCountryCode: "NZ",
    countryName: "New Zealand",
    population: "4252277",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NI: {
    isoCountryCode: "NI",
    countryName: "Nicaragua",
    population: "5995928",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NE: {
    isoCountryCode: "NE",
    countryName: "Niger",
    population: "15878271",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NG: {
    isoCountryCode: "NG",
    countryName: "Nigeria",
    population: "154000000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  NU: {
    isoCountryCode: "NU",
    countryName: "Niue",
    population: "2166",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NZ",
  },
  NF: {
    isoCountryCode: "NF",
    countryName: "Norfolk Island",
    population: "1828",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "AU",
  },
  MP: {
    isoCountryCode: "MP",
    countryName: "Northern Mariana Islands",
    population: "53883",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
  },
  NO: {
    isoCountryCode: "NO",
    countryName: "Norway",
    population: "5009150",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  OM: {
    isoCountryCode: "OM",
    countryName: "Oman",
    population: "2967717",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PK: {
    isoCountryCode: "PK",
    countryName: "Pakistan",
    population: "184404791",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PW: {
    isoCountryCode: "PW",
    countryName: "Palau",
    population: "19907",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PS: {
    isoCountryCode: "PS",
    countryName: "Palestinian Territory, Occupied",
    population: "3800000",
    sovereigntyLevel: SovereigntyLevel.UNObserver,
  },
  PA: {
    isoCountryCode: "PA",
    countryName: "Panama",
    population: "3410676",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PG: {
    isoCountryCode: "PG",
    countryName: "Papua New Guinea",
    population: "6064515",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PY: {
    isoCountryCode: "PY",
    countryName: "Paraguay",
    population: "6375830",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PE: {
    isoCountryCode: "PE",
    countryName: "Peru",
    population: "29907003",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PH: {
    isoCountryCode: "PH",
    countryName: "Philippines",
    population: "99900177",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PN: {
    isoCountryCode: "PN",
    countryName: "Pitcairn",
    population: "46",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  PL: {
    isoCountryCode: "PL",
    countryName: "Poland",
    population: "38500000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PT: {
    isoCountryCode: "PT",
    countryName: "Portugal",
    population: "10676000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  PR: {
    isoCountryCode: "PR",
    countryName: "Puerto Rico",
    population: "3916632",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
  },
  QA: {
    isoCountryCode: "QA",
    countryName: "Qatar",
    population: "840926",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  RE: {
    isoCountryCode: "RE",
    countryName: "Reunion",
    population: "776948",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  RO: {
    isoCountryCode: "RO",
    countryName: "Romania",
    population: "21959278",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  RU: {
    isoCountryCode: "RU",
    countryName: "Russian Federation",
    population: "140702000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  RW: {
    isoCountryCode: "RW",
    countryName: "Rwanda",
    population: "11055976",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  BL: {
    isoCountryCode: "BL",
    countryName: "Saint Barthelemy",
    population: "8450",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  SH: {
    isoCountryCode: "SH",
    countryName: "Saint Helena",
    population: "7460",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  KN: {
    isoCountryCode: "KN",
    countryName: "Saint Kitts And Nevis",
    population: "51134",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LC: {
    isoCountryCode: "LC",
    countryName: "Saint Lucia",
    population: "160922",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  MF: {
    isoCountryCode: "MF",
    countryName: "Saint Martin",
    population: "35925",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  PM: {
    isoCountryCode: "PM",
    countryName: "Saint Pierre And Miquelon",
    population: "7012",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  VC: {
    isoCountryCode: "VC",
    countryName: "Saint Vincent And Grenadines",
    population: "104217",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  WS: {
    isoCountryCode: "WS",
    countryName: "Samoa",
    population: "192001",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SM: {
    isoCountryCode: "SM",
    countryName: "San Marino",
    population: "31477",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ST: {
    isoCountryCode: "ST",
    countryName: "Sao Tome And Principe",
    population: "211028",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SA: {
    isoCountryCode: "SA",
    countryName: "Saudi Arabia",
    population: "25731776",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SN: {
    isoCountryCode: "SN",
    countryName: "Senegal",
    population: "12323252",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  RS: {
    isoCountryCode: "RS",
    countryName: "Serbia",
    population: "7344847",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SC: {
    isoCountryCode: "SC",
    countryName: "Seychelles",
    population: "88340",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SL: {
    isoCountryCode: "SL",
    countryName: "Sierra Leone",
    population: "5245695",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SG: {
    isoCountryCode: "SG",
    countryName: "Singapore",
    population: "4701069",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SK: {
    isoCountryCode: "SK",
    countryName: "Slovakia",
    population: "5455000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SI: {
    isoCountryCode: "SI",
    countryName: "Slovenia",
    population: "2007000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SB: {
    isoCountryCode: "SB",
    countryName: "Solomon Islands",
    population: "559198",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SO: {
    isoCountryCode: "SO",
    countryName: "Somalia",
    population: "10112453",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SS: {
    isoCountryCode: "SS",
    countryName: "South Sudan",
    population: "12778250",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ZA: {
    isoCountryCode: "ZA",
    countryName: "South Africa",
    population: "49000000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GS: {
    isoCountryCode: "GS",
    countryName: "South Georgia And Sandwich Isl.",
    population: "30",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  ES: {
    isoCountryCode: "ES",
    countryName: "Spain",
    population: "46505963",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  LK: {
    isoCountryCode: "LK",
    countryName: "Sri Lanka",
    population: "21513990",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SD: {
    isoCountryCode: "SD",
    countryName: "Sudan",
    population: "41592539",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SR: {
    isoCountryCode: "SR",
    countryName: "Suriname",
    population: "492829",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SJ: {
    isoCountryCode: "SJ",
    countryName: "Svalbard And Jan Mayen",
    population: "2550",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NO",
  },
  SZ: {
    isoCountryCode: "SZ",
    countryName: "Eswatini",
    population: "1354051",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SE: {
    isoCountryCode: "SE",
    countryName: "Sweden",
    population: "9828655",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  CH: {
    isoCountryCode: "CH",
    countryName: "Switzerland",
    population: "7581000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  SY: {
    isoCountryCode: "SY",
    countryName: "Syrian Arab Republic",
    population: "22198110",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TW: {
    isoCountryCode: "TW",
    countryName: "Taiwan",
    population: "22894384",
    sovereigntyLevel: SovereigntyLevel.Disputed,
  },
  TJ: {
    isoCountryCode: "TJ",
    countryName: "Tajikistan",
    population: "7487489",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TZ: {
    isoCountryCode: "TZ",
    countryName: "Tanzania",
    population: "41892895",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TH: {
    isoCountryCode: "TH",
    countryName: "Thailand",
    population: "67089500",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TL: {
    isoCountryCode: "TL",
    countryName: "Timor-Leste",
    population: "1154625",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TG: {
    isoCountryCode: "TG",
    countryName: "Togo",
    population: "6587239",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TK: {
    isoCountryCode: "TK",
    countryName: "Tokelau",
    population: "1466",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "NZ",
  },
  TO: {
    isoCountryCode: "TO",
    countryName: "Tonga",
    population: "122580",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TT: {
    isoCountryCode: "TT",
    countryName: "Trinidad And Tobago",
    population: "1228691",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TN: {
    isoCountryCode: "TN",
    countryName: "Tunisia",
    population: "10589025",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TR: {
    isoCountryCode: "TR",
    countryName: "Turkey",
    population: "77804122",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TM: {
    isoCountryCode: "TM",
    countryName: "Turkmenistan",
    population: "4940916",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  TC: {
    isoCountryCode: "TC",
    countryName: "Turks And Caicos Islands",
    population: "20556",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  TV: {
    isoCountryCode: "TV",
    countryName: "Tuvalu",
    population: "10472",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  UG: {
    isoCountryCode: "UG",
    countryName: "Uganda",
    population: "33398682",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  UA: {
    isoCountryCode: "UA",
    countryName: "Ukraine",
    population: "45415596",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  AE: {
    isoCountryCode: "AE",
    countryName: "United Arab Emirates",
    population: "4975593",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  GB: {
    isoCountryCode: "GB",
    countryName: "United Kingdom",
    population: "62348447",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  US: {
    isoCountryCode: "US",
    countryName: "United States",
    population: "310232863",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  UM: {
    isoCountryCode: "UM",
    countryName: "United States Outlying Islands",
    population: "0",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
  },
  UY: {
    isoCountryCode: "UY",
    countryName: "Uruguay",
    population: "3477000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  UZ: {
    isoCountryCode: "UZ",
    countryName: "Uzbekistan",
    population: "27865738",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  VU: {
    isoCountryCode: "VU",
    countryName: "Vanuatu",
    population: "221552",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  VE: {
    isoCountryCode: "VE",
    countryName: "Venezuela",
    population: "27223228",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  VN: {
    isoCountryCode: "VN",
    countryName: "Vietnam",
    population: "89571130",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  VG: {
    isoCountryCode: "VG",
    countryName: "Virgin Islands, British",
    population: "21730",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "GB",
  },
  VI: {
    isoCountryCode: "VI",
    countryName: "Virgin Islands, U.S.",
    population: "108708",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "US",
  },
  WF: {
    isoCountryCode: "WF",
    countryName: "Wallis And Futuna",
    population: "16025",
    sovereigntyLevel: SovereigntyLevel.Territory,
    parentCountry: "FR",
  },
  EH: {
    isoCountryCode: "EH",
    countryName: "Western Sahara",
    population: "273008",
    sovereigntyLevel: SovereigntyLevel.Disputed,
  },
  YE: {
    isoCountryCode: "YE",
    countryName: "Yemen",
    population: "23495361",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ZM: {
    isoCountryCode: "ZM",
    countryName: "Zambia",
    population: "13460305",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
  ZW: {
    isoCountryCode: "ZW",
    countryName: "Zimbabwe",
    population: "13061000",
    sovereigntyLevel: SovereigntyLevel.UNMemberState,
  },
};

export function getCountryData(): Map<string, CountryDatum> {
  const countryDataMap = new Map();

  for (const rawCountryDatum of Object.values(rawCountryData)) {
    const countryDatum: CountryDatum = {
      ...rawCountryDatum,
      population: Number(rawCountryDatum.population),
    };

    countryDataMap.set(countryDatum.isoCountryCode, countryDatum);
  }

  return countryDataMap;
}
